export enum TwingNodeType {
    AUTO_ESCAPE = 'auto_escape',
    BLOCK = 'block',
    BLOCK_REFERENCE = 'block_reference',
    BODY = 'body',
    DO = 'do',
    EXPRESSION_ARRAY = 'expression_array',
    EXPRESSION_ASSIGN_NAME = 'expression_assign_name',
    EXPRESSION_BINARY = 'expression_binary',
    EXPRESSION_BLOCK_REFERENCE = 'expression_block_reference',
    EXPRESSION_CONDITIONAL = 'expression_conditional',
    EXPRESSION_CONSTANT = 'expression_constant',
    EXPRESSION_FILTER = 'expression_filter',
    EXPRESSION_FUNCTION = 'expression_function',
    EXPRESSION_GET_ATTR = 'expression_get_attr',
    EXPRESSION_METHOD_CALL = 'expression_method_call',
    EXPRESSION_NAME = 'expression_name',
    EXPRESSION_NULL_COALESCE = 'expression_null_coalesce',
    EXPRESSION_PARENT = 'expression_parent',
    EXPRESSION_TEST = 'expression_test',
    EXPRESSION_UNARY = 'expression_unary',
    EXPRESSION_UNARY_NEG = 'expression_unary_neg',
    EXPRESSION_UNARY_POS = 'expression_unary_pos',
    FLUSH = 'flush',
    FOR = 'for',
    IF = 'if',
    IMPORT = 'import',
    INCLUDE = 'include',
    MACRO = 'macro',
    MODULE = 'module',
    PRINT = 'print',
    SANDBOX = 'sandbox',
    SET = 'set',
    SPACELESS = 'spaceless',
    TEXT = 'text'
}

export default TwingNodeType;